### ISSUE TITLE
Bug na criação de pauta

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/marcocivil-tema#15]
Bug na criação de pauta, box de texto não aparece.
![captura de tela de 2015-02-10 15_07_58](https://cloud.githubusercontent.com/assets/3003517/6146399/f4af6ab6-b1ca-11e4-937d-76d3c3bd9502.png)
![captura de tela de 2015-02-10 15_08_04](https://cloud.githubusercontent.com/assets/3003517/6146400/f4b019fc-b1ca-11e4-8474-0d3c1c6f8920.png)

**Comment by thsl** [comment]
Finalizado!
