### ISSUE TITLE
Filtro fixo dos eixos está ficando por baixo da lista de pautas

### ISSUE THREAD

**Issue by eduardozulian** [pensandoodireito/marcocivil-tema#16]
Em http://participacao.mj.gov.br/marcocivil/pauta/, o filtro de eixos que é fixado à esquerda na rolagem da página está ficando por baixo da lista de pautas, o que impossibilita o clique e confunde a leitura. Usando o Safari, um `z-index` funcionou pra mim perfeitamente.

![captura](https://cloud.githubusercontent.com/assets/1136160/6557637/437e7c74-c655-11e4-9370-6ed9d308b51c.png)

**Comment by diraol** [comment]
@eduardozulian, obrigado pelo report.
@marcoamarelo, na versão que está rodando na minha máquina o tema está funcionando corretamente. O último commit no que está na minha máquina foi o 22e4da0 (inclusão da função para inclusão de metas especiais no header do site). Talvez precise só atualizar na versão em produção, acho que vale conferir.

**Comment by marcoamarelo** [comment]
Obrigado pelo report @eduardozulian.

O problema foi corrigido.

Atenciosamente,

Marco Antonio Konopacki

## @marcoamarelo

...... __@
...._ \ >_
...(_)/ (_)

Em 9 de março de 2015 14:00, Diego Rabatone Oliveira <
notifications@github.com> escreveu:

**Comment by eduardozulian** [comment]
Valeu, galera! :facepunch:
